Cuantos tokens para el ejemplo???

MAYUSCULAS minusculas Letras Letr4 Id3nt1f1c4d0r
0 0123 +0123 -0123e2 10E2 10e10 +12E34
-12.05E34
verdadero falso
"a" "/""
'asdf/'asdf'
{hola} {hola/}adios}
accion
algoritmo
booleano
cadena
caracter
const
continuar
de
dev
div
ent
entero
e\/s
faccion
falgoritmo
falso
fconst
ffuncion
fmientras
fpara
fsi
ftipo
ftupla
funcion
fvar
hacer
hasta
mientras
mod
no
o
para
real
ref
sal
si
tabla
tipo
tupla
var
verdadero
y
< <= > >= <> != ==


